-- CREANDO FUNCIONES

DELIMITER $$
CREATE FUNCTION `UserLevel` (PARAM1 INT) RETURNS VARCHAR(10)
NO SQL
BEGIN
	DECLARE resultado VARCHAR(10);
    IF PARAM1 > 0 THEN
		SET resultado = 'NO ES ADMIN';
	ELSEIF PARAM1 = 0 THEN
		SET resultado = 'ES ADMIN';
	END IF;
    RETURN resultado;
END$$
DELIMITER ;


DELIMITER $$
CREATE FUNCTION `PromedioKPI` () RETURNS FLOAT
READS SQL DATA
BEGIN
    RETURN (
    SELECT AVG(kpis.puntaje_usuario) AS CONTANDO FROM kpis
    );
END$$
DELIMITER ;
